version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - python --version  # Confirm Python is installed
      - pip install -r requirements.txt  # Install dependencies
  build:
    commands:
      - echo Building the application...
      - python setup.py build  # Example: Adjust for your Python application
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - '**/*'

